FROM golang:1.21-alpine

WORKDIR /app

# Копируем go.mod
COPY go.mod ./

# Копируем исходный код
COPY main.go ./

# Собираем приложение
RUN go build -o auth-service main.go

EXPOSE 8081

CMD ["./auth-service"]