apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.owner }}
  password: apppassword
