apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-app-config
  namespace: default
data:
  NAME: "Kubernetes"
  BG_COLOR: "#0f172a"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "appuser"
